### ISSUE TITLE
WebRTC not supported

### ISSUE THREAD

**Issue by mudrd8mz** [moodleou/moodle-qtype_recordrtc#1]
I cannot get rid of the error message:
```
WebRTC not supported

Your browser offers limited or no support for WebRTC technologies yet, and cannot be used with this
type of question. Please switch or upgrade your browser.
```
whenever I try this. Attempted with Firefox 71.0 (64-bit) and Chrome 79.0.3945.79 (Official Build) (64-bit) on Linux, each with and without OpenGL / 3D discrete GPU available. 

This seems clearly to be a local issue, I am just wondering if there are some debugging hints available as to what might be missing in my setup. TIA.

**Comment by timhunt** [comment]
That is strange. On the same computer, does the Record RTC button in atto work? We basically stole all that code, including the browser compatibility checks (https://github.com/moodle/moodle/blob/master/lib/editor/atto/plugins/recordrtc/yui/src/recording/js/compatcheckmodule.js#L41), although we then rewrote it to eliminate the YUI.

Firefox supports all the the necessary APIs, and we are using ogg format, so I would expect it to work.

**Comment by mudrd8mz** [comment]
No, it does not work in Atto, too.

**Comment by timhunt** [comment]
OK. I wonder what the difference is between Firefox on Win/Max and Firefox on Linux. Not something I am in a position to easily debug.

**Comment by mudrd8mz** [comment]
Aha! I think I got something. The Atto record button _does_ work if I access the site via HTTPS. And I recall it has been a requirement for some of these features.

**Comment by mudrd8mz** [comment]
And yes, I can confirm that once I access my local testing environment under HTTPS, it works.

**Comment by timhunt** [comment]
Yes, that is a requirement for these APIs. The Atto plugin gives a more specific error message in this case. We shuld probably do the same. Thank you for reporting the issue, and your help with diagnosis. Now we just need time to fix is.

**Comment by timhunt** [comment]
We now have a more specific error message for this case. Closing.
