### ISSUE TITLE
Add User and Attempt Details to file names (Improvement / Feature Request)

### ISSUE THREAD

**Issue by rkr1209** [moodleou/moodle-qtype_recordrtc#13]
Hi there!

I'd have an improvement / feature request:

Can the user's id, name and the attempt id be added to the downloaded filename?

For example, instead of having 
recording.mp3 / recording.webm
have file names like
recording_USERID_STUDENTNAME_ATTEMPTID.mp3 / .webm
(recording_283_johndoe_53.mp3)

This would be a great improvement, especially when the recorded files are downloaded by teachers for archiving locally, so they don't have to rename each file manually.

**Comment by timhunt** [comment]
I don't think this feature should be added to this question type. The experience should be optimised for the student attemting the quiz.

If you want an archiving solution, try https://moodle.org/plugins/quiz_answersheets or one of the other similar plugins.
