### ISSUE TITLE
How to Download all the Audio response submitted in a quiz?

### ISSUE THREAD

**Issue by raghebalghezi** [moodleou/moodle-qtype_recordrtc#5]
I was wondering if there is a way to bulk-download all audio responses submitted to a quiz (an equivalent for the one in Assignment activity see below). If not, could you please guide me on where to collect them? e.g. location in db, etc.
![example](https://sites.up.edu/moodle/wp-content/uploads/sites/257/2017/10/dl-3.png)

**Comment by timhunt** [comment]
The same question could be asked of other question types, such as qype_essay (where the student uploads attachments).

This shows that the answer is not specific to this question type. Have a looks at https://moodle.org/plugins/quiz_answersheets.
