### ISSUE TITLE
record_rtc audiofile location

### ISSUE THREAD

**Issue by katildakat** [moodleou/moodle-qtype_recordrtc#6]
Hello!

We backed up a course containing students' recordings (using your record_rtc plugin), but when we tried to restore the backup, the audio responses were not restored. Investigating the activity backup file `.mbz`, we could not find the audio recording files in the files folder of .mbz archive. We suspect that the information about these recordings is still stored somewhere in the archive, but not the files themselves.

Do you have any idea where Moodle stores these recordings (server location or database location)? Even better, if you can give advice on how to download students’ audio responses alongside their user information?

**Comment by timhunt** [comment]
Moodle stores these files the same place that it stores all files related to students answers to questions (e.g. files attached to essay qeustion responses).
