### ISSUE TITLE
PHP 7.0 compatibility problem: syntax error, unexpected '?', expecting variable (T_VARIABLE)

### ISSUE THREAD

**Issue by fishfree** [moodleou/moodle-qtype_recordrtc#7]
After enabling developper debug mode, it reports the line 146 in the file renderer.php causing this problem:
`protected function recording_ui(string $filename, ?moodle_url $recordingurl,`

**Comment by timhunt** [comment]
qtype_recordrtc does not support PHP 7.0. (Nor does PHP https://www.php.net/supported-versions.php.) You will need to upgrade if you want to use our question type.

**Comment by fishfree** [comment]
I deleted the type declaration ?moodle_url in that file and the other one in question.php ?stored_file. It then works nicely with PHP 7.0.
